sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 5201314zh
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password: 5201314zh
    database: 10
  wechat:
    appid: wxa38a4d653d77a254
    secret: 4155df2388c9186047fa4782df6ecf53